server:
  port: 31001

spring:
  data:
    mongodb:
      database: dl_cms
      uri: mongodb://192.168.1.109:27017
      username: root
      password: 123456
  application:
    name: cms-server

  freemarker:
    cache: false  # 关闭模板缓存，方便测试
    settings:
      template_update_delay : 0
